advocate_management/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'home#index'
  mount LetterOpenerWeb::Engine, at: "/mails" if Rails.env.development?
  devise_for :users
  resources :juniors
  post "/add_juniors" => "juniors#add_juniors"
  resources :cases do
  	get :reject
  end
end

advocate_management/app/controllers/juniors_controller.rb
class JuniorsController < ApplicationController
	before_action :set_junior, only: [:edit, :update, :destroy]
	before_action :check_user
	before_action :load_existing_juniors, only: [:new, :create]
	def index
		@juniors = current_user.juniors
	end

	def new
		@junior = User.new
		@existing_juniors = User.all_juniors.map{|jun| ["#{jun.name}(#{jun.advocate_number})", jun.id]}
	end

	def create
		@junior = current_user.juniors.new(junior_params)
		if @junior.save
			redirect_to juniors_path, notice: "Junior Advocate added successfully"
		else
			render :new
		end
	end

	def edit
		
	end

	def update
		if @junior.update(junior_params)
			redirect_to juniors_path, notice: "Junior Advocate updated successfully"
		else
			render :edit
		end
	end

	def destroy
		@junior.update(user_id: nil)
		redirect_to juniors_path, notice: "Junior Advocate removed successfully"

	end

	def add_juniors
		@juniors = User.where(id: params[:juniors]).update_all(user_id: current_user.id)
		redirect_to juniors_path, notice: "Junior Advocate added successfully"
	end

	private
		def set_junior
			@junior = User.find(params[:id])
		end

		def check_user
			redirect_to root_path, alert: "Unauthorized Access!" if current_user.junior_lawyer?
		end

		def junior_params
			params.require(:user).permit(:email, :user_id, :mobile_number, :first_name, :last_name, :phone_number, :date_of_birth, :role, :is_auto_pwd, :advocate_number, {state_ids: []})
		end

		def load_existing_juniors
			@existing_juniors = User.all_juniors.map{|jun| ["#{jun.name}(#{jun.advocate_number})", jun.id]}
		end
end

advocate_management/app/helpers/juniors_helper.rb
module JuniorsHelper

	def form_url
		@junior.new_record? ? juniors_path : junior_path(@junior)
	end
end

advocate_management/app/views/juniors/_form.html.erb
<div class="d-sm-flex align-items-center justify-content-between mb-4">
  <h1 class="h3 mb-0 text-gray-800"><%= @junior.new_record? ? "New" : "Edit"%> Junior</h1>
  <a href="#" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm"><i class="fas fa-arrow-left fa-sm text-white-50"></i> Back</a>
</div>

<!-- Content Row -->
<div class="row">
	<%if @junior.new_record?%>
		<div class="col-12 mb-4">
	    <div class="card border-left-primary shadow h-100 py-2">
	      <div class="card-body">
	      	<%= form_tag add_juniors_path, method: "post" do%>
		      	<h5>Add from Registered Juniors</h5> <small class="text-danger">Note: Junior who are all registered in this Application</small>
		      	<div class="row">
		      		<div class="col-12 form-group">
		      			<%= select_tag :juniors, options_for_select(@existing_juniors), { class: "chosen-select form-control", multiple: true, data: {placeholder: "Select Junior"}, required: true}%>
		      		</div>
		      		<div class="col-12 form-group">
		      			<button class="btn btn-sm btn-success">Add Junior</button>
		      		</div>
		      	</div>
		      <% end -%>
	      </div>
	    </div>
	  </div>
	  <div class="col-12"><h5 class="text-center">Or</h5></div>
	<% end -%>
  <div class="col-12">
    <div class="card border-left-primary shadow h-100 py-2">
      <div class="card-body">
      	<%= form_for @junior, url: form_url, method: (@junior.new_record? ? "post" : "patch") do |f|%>
      		<%=f.hidden_field :user_id, value: current_user.id%>
      		<%=f.hidden_field :role, value: AppConstants::ROLE_JUNIOR_LAWYER%>
      		<%=f.hidden_field :is_auto_pwd, value: true%>
      		<%= render "shared/user_fields", f: f%>
      		<div class="row">
      			<div class="col-12">
      				<%= f.submit "Save", class: "btn btn-sm btn-success"%>
      			</div>
      		</div>
      	<% end -%>
      </div>
    </div>
  </div>
</div>

<%if @junior.errors.any?%>
<script>
  $errors = <%=@junior.errors.to_json.html_safe%>
</script>
<% end -%>

advocate_management/app/views/juniors/_junior_tr.html.erb
<tr>
	<td><%= sno%></td>
	<td><%= junior.name%></td>
	<td><%= junior.advocate_number%></td>
	<td><%= junior.contact_details%></td>
	<td><%= junior.states.pluck(:name).join(",")%></td>
	<td>
		<%= link_to edit_junior_path(junior), class: "btn btn-sm btn-warning" do%>
			<i class="fas fa-edit"></i> Edit
		<% end -%>
		<%= link_to junior_path(junior), method: :delete, data: {confirm: "Are you sure you want to delete this junior?"}, class: "btn btn-sm btn-danger" do%>
			<i class="fas fa-trash"></i> Delete
		<% end -%>
	</td>
</tr>

advocate_management/app/views/juniors/edit.html.erb
<%= render 'form'%>

advocate_management/app/views/juniors/index.html.erb
<div class="d-sm-flex align-items-center justify-content-between mb-4">
  <h1 class="h3 mb-0 text-gray-800">Junior Lawyers</h1>
  <a href="#" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm"><i class="fas fa-arrow-left fa-sm text-white-50"></i> Back</a>
</div>

<!-- Content Row -->
<div class="row">

  <!-- Earnings (Monthly) Card Example -->
  <div class="col-12 mb-4">
    <div class="card border-left-primary shadow h-100 py-2">
      <div class="card-body">
        <div class="row">
        	<div class="col-12 form-group">
        		<%= link_to new_junior_path, class: "btn btn-primary btn-sm float-right" do%>
        			<i class="fas fa-plus"></i> New Junior
        		<% end -%>
        	</div>
        	<div class="col-12 table-responsive">
        		<table class="table table-bordered table-striped">
        			<thead>
        				<tr>
        					<th>S.No</th>
        					<th>Junior Name</th>
        					<th>Advocate Reg. Number</th>
        					<th>Contact Details</th>
        					<th>Serving States</th>
        					<th>Action</th>
        				</tr>
        			</thead>
        			<tbody>
        				<%if @juniors.present?%>
                  <%@juniors.each_with_index do |junior, i|%>
                    <%= render 'juniors/junior_tr', sno: i+1, junior: junior%>
                  <% end -%>
                <%else%>
                  <%=render 'shared/no_records', colspan: 6%>
                <%end%>
        			</tbody>
        		</table>
        	</div>
        </div>
      </div>
    </div>
  </div>
</div>

advocate_management/app/views/juniors/new.html.erb
<%= render 'form'%>