advocate_management/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'home#index'
  mount LetterOpenerWeb::Engine, at: "/mails" if Rails.env.development?
  devise_for :users
  resources :juniors
  post "/add_juniors" => "juniors#add_juniors"
  resources :cases do
  	get :reject
  end
end

advocate_management/app/views/layouts/shared/_flash_messages.html.erb
<script>
  // $( document ).on('ready', function() {
    if($errors != undefined && $errors != null){
      for(var key in $errors){
        if ($errors.hasOwnProperty(key)) {
          if ($errors[key].length > 0) {
            toastr.error(key.capitalize() +" "+ $errors[key].join(", "))
            // toastr.error($errors[key].join(", "))
          }
        }
      }
    }
    <%flash.each do |msg_type, message|%>
      <%msg_type = (msg_type == 'notice') ? "success" : msg_type%>
      <%msg_type = (msg_type == 'alert') ? "error" : msg_type%>
      setTimeout(function(){
        toastr["<%=msg_type%>"]("<%=message%>")
      }, 100)
    <%end%>
  // })
</script>

advocate_management/app/views/layouts/shared/_logout_modal.html.erb
  <!-- Logout Modal-->
  <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
          <button class="close" type="button" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">×</span>
          </button>
        </div>
        <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
        <div class="modal-footer">
          <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
          <a class="btn btn-primary" data-method="delete" href="<%= destroy_user_session_path%>">Logout</a>
        </div>
      </div>
    </div>
  </div>

advocate_management/app/views/layouts/shared/_messages.html.erb
<li class="nav-item dropdown no-arrow mx-1">
  <a href="#" class="nav-link dropdown-toggle" id="messagesDropdown" 
    role="button" data-toggle="dropdown" aria-haspopup="true" 
    aria-expanded="false">
    <i class="fas fa-envelope fa-fw"></i>

    <!-- Counter - Messages -->
    <% if @messages.present? %>
      <span class="badge badge-danger badge-counter">
        <%= @messages.size %>
      </span>
    <% end %>
  </a>

  <!-- Dropdown - Messages -->
  <div aria-labelledby="messagesDropdown"
    class="dropdown-list dropdown-menu dropdown-menu-right
           shadow animated--grow-in">

    <h6 class="dropdown-header">
      Message Center
    </h6>

    <% @messages&.each do |message| %>
    <a class="dropdown-item d-flex align-items-center" href="#">
      <div class="dropdown-list-image mr-3">
        <img class="rounded-circle" src="<%= message.sender_avatar %>" alt="">
        <div class="status-indicator bg-success"></div>
      </div>
      <div class="font-weight-bold">
        <div class="text-truncate"><%= message.content %></div>
        <div class="small text-gray-500"><%= message.sender %></div>
      </div>
    </a>
    <% end %>

    <a class="dropdown-item text-center small text-gray-500" href="#">
      Read More Messages
    </a>
  </div>
</li>

advocate_management/app/views/layouts/shared/_notifications.html.erb
<li class="nav-item dropdown no-arrow mx-1">
  <a class="nav-link dropdown-toggle" href="#" id="alertsDropdown" 
    role="button" data-toggle="dropdown"aria-haspopup="true"
    aria-expanded="false">
    <i class="fas fa-bell fa-fw"></i>

    <!-- Counter - Alerts -->
    <% if @notifications.present? %>
      <span class="badge badge-danger badge-counter">
        <%= @notifications.size %>+
      </span>
    <% end %>
  </a>

  <!-- Dropdown - Alerts -->
  <div aria-labelledby="alertsDropdown"
    class="dropdown-list dropdown-menu dropdown-menu-right 
           shadow animated--grow-in">

    <h6 class="dropdown-header">
      Alerts Center
    </h6>

    <% @notifications&.each do |notification| %>
    <a class="dropdown-item d-flex align-items-center" href="#">
      <div class="mr-3">
        <div class="icon-circle bg-<%= notification.kind %>">
          <i class="fas fa-file-alt text-white"></i>
        </div>
      </div>
      <div>
        <div class="small text-gray-500"><%= notification.date %></div>
        <% if notification.viewed %>
          <%= notification.content %>
        <% else %>
          <span class="font-weight-bold"><%= notification.content %></span>
        <% end %>
      </div>
    </a>
    <% end %>

    <a class="dropdown-item text-center small text-gray-500" href="#">
      Show All Alerts
    </a>
  </div>
</li>

advocate_management/app/views/layouts/shared/_search_dropdown.html.erb
<li class="nav-item dropdown no-arrow d-sm-none">
  <a class="nav-link dropdown-toggle" href="#" id="searchDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    <i class="fas fa-search fa-fw"></i>
  </a>
  <!-- Dropdown - Messages -->
  <div class="dropdown-menu dropdown-menu-right p-3 shadow animated--grow-in" aria-labelledby="searchDropdown">
    <form class="form-inline mr-auto w-100 navbar-search">
      <%= render "layouts/shared/search_field" %>
    </form>
  </div>
</li>

advocate_management/app/views/layouts/shared/_search_field.html.erb
<div class="input-group">
  <input type="text" class="form-control bg-light border-0 small" placeholder="Search for..." aria-label="Search" aria-describedby="basic-addon2">
  <div class="input-group-append">
    <button class="btn btn-primary" type="button">
      <i class="fas fa-search fa-sm"></i>
    </button>
  </div>
</div>

advocate_management/app/views/layouts/shared/_sidebar.html.erb
<!-- Sidebar -->
<ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

  <!-- Sidebar - Brand -->
  <a class="sidebar-brand d-flex align-items-center justify-content-center" href="<%= root_path %>">
    <div class="sidebar-brand-icon rotate-n-15s">
      <img src="/logo.png" width="50" height="50" alt="">
    </div>
    <div class="sidebar-brand-text mx-3">Advocate <sup>Management</sup></div>
  </a>

  <!-- Divider -->
  <hr class="sidebar-divider my-0">

  <!-- Nav Item - Dashboard -->
  <li class="nav-item <%= add_active_class(root_path) %>">
    <a class="nav-link" href="<%= root_path %>">
      <i class="fas fa-fw fa-tachometer-alt"></i>
      <span>Dashboard</span></a>
  </li>

  <%if current_user.senior_lawyer?%>
    <li class="nav-item <%= add_active_class(juniors_path) %>">
      <a class="nav-link" href="<%= juniors_path %>">
        <i class="fas fa-fw fa-gavel"></i>
        <span>Junior Lawyers</span></a>
    </li>
  <% end -%>
  <li class="nav-item <%= add_active_class(edit_user_registration_path(current_user)) %>">
    <a class="nav-link" href="<%= edit_user_registration_path(current_user) %>">
      <i class="fas fa-fw fa-cogs"></i>
      <span>Settings</span></a>
  </li>
  <li class="nav-item <%= add_active_class(cases_path) %>">
    <a class="nav-link" href="<%= cases_path %>">
      <i class="fas fa-fw fa-file-signature"></i>
      <span>Cases</span></a>
  </li>
  <!-- Divider -->
  <hr class="sidebar-divider d-none d-md-block">

  <!-- Sidebar Toggler (Sidebar) -->
  <div class="text-center d-none d-md-inline">
    <button class="rounded-circle border-0" id="sidebarToggle"></button>
  </div>

</ul>
<!-- End of Sidebar -->

advocate_management/app/views/layouts/shared/_topbar.html.erb
<nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

  <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
    <i class="fa fa-bars"></i>
  </button>

  <ul class="navbar-nav ml-auto">
    <%#= render "layouts/shared/search_dropdown" %>
    <%#= render "layouts/shared/notifications" %>
    <%#= render "layouts/shared/messages" %>

    <div class="topbar-divider d-none d-sm-block"></div>

    <%= render "layouts/shared/user_nav" %>
  </ul>

</nav>

advocate_management/app/views/layouts/shared/_user_nav.html.erb
<li class="nav-item dropdown no-arrow">
  <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    <span class="mr-2 d-none d-lg-inline text-gray-600 small"><%= current_user.name%></span>
    <img class="img-profile rounded-circle" src="https://source.unsplash.com/QAB-WJcbgJk/60x60">
  </a>
  <!-- Dropdown - User Information -->
  <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="userDropdown">
    <a class="dropdown-item" href="<%=edit_user_registration_path(current_user)%>">
      <i class="fas fa-cogs fa-sm fa-fw mr-2 text-gray-400"></i>
      Settings
    </a>
    <div class="dropdown-divider"></div>
    <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">
      <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
      Logout
    </a>
  </div>
</li>